version: '3.8'

services:
  app:
    build: .
    restart: always
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    env_file:
      - .env

  postgres:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=\
      - POSTGRES_PASSWORD=\
      - POSTGRES_DB=\
    ports:
      - "5432:5432"

  redis:
    image: redis:6-alpine
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  postgres-data:
  redis-data:
